apiVersion: v1
kind: Service
metadata:
  name: publicui
spec:
  selector:
    app: publicui
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publicui
  template:
    metadata:
      labels:
        app: publicui
    spec:
      containers:
      - name: publicui
        image: {acr-prefix}.azurecr.io/publicui:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
